services:
  nginx:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    ports:
      - '${NGINX_HTTP_PORT}:80'
      - '${NGINX_ADMIN_PORT}:81'
      - '${NGINX_HTTPS_PORT}:443'
    volumes:
      - '${DOCKER_DATA}/nginx/nginx:/data'
      - '${DOCKER_DATA}/niginx/letsencrypt:/etc/letsencrypt'
      - 'nginxlogs:/data/logs
    healthcheck:
      test: ["CMD", "/usr/bin/check-health"]
      interval: 10s
      timeout: 3s
    restart: unless-stopped

  fail2ban:
    container_name: fail2ban
    image: crazymax/fail2ban:latest
    hostname: fail2ban
    cap_add:
      - NET_ADMIN
      - NET_RAW
    network_mode: host
    volumes:
      - '${NGINX_DATA}/fail2ban:/data'
      - nginxlogs:/var/log/npm
    restart: unless-stopped

  goaccess:
    image: justsky/goaccess-for-nginxproxymanager:latest
    container_name: goaccess
    ports:
      - "${GOACCESS_HTTP_PORT}:7880"
    volumes:
      - nginxlogs:/opt/log
      - '${DOCKER_DATA}/nginx/goaccess:/config'
    environment:
      - TZ=${TZ}
    restart: unless-stopped
volumes:
  nginxlogs:
  
